[package]
edition = "2021"
name = "napi-test"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.0.0-beta.2"
napi-derive = "2.0.0-beta.1"

[build-dependencies]
napi-build = "1.2"
